//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical5
{


    public partial class Home
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.Label Label1;

        protected global::System.Web.UI.WebControls.TextBox txtId;

        protected global::System.Web.UI.WebControls.Label Label2;

        protected global::System.Web.UI.WebControls.TextBox txtPass;

        protected global::System.Web.UI.WebControls.Button btnLogin;
    }
}
